[[headers]]
  for = "**/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
